name: Tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Specify node version
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Install node_modules
        run: npm install

      - name: Run tests
        run: npm test

      - name: Run type checks
        run: npm run type-check
