name: Tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Specify node version
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install node_modules
        run: npm i

      - name: Run tests
        run: npm test
